spring.application.name=jsf-test

spring.datasource.url=jdbc:postgresql://localhost:5432/petshop
spring.datasource.username=petshop
spring.datasource.password=petshop

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

joinfaces.faces.project-stage=development
joinfaces.faces.facelets-refresh-period=0

